pipeline:
  name: fdvgdsfgv
  identifier: fdvgdsfgv
  projectIdentifier: test_adithya
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fdg
        identifier: fdg
        tags: {}
        template:
          templateRef: test_remote_template_12312
          versionLabel: fdv
          gitBranch: master
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: fda
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
