pipeline:
  name: pipelint stage
  identifier: pipelint_stage
  projectIdentifier: test_adithya
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: asd
        identifier: asd
        tags: {}
        template:
          templateRef: stage_template_defualt
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: as
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
