pipeline:
  name: PIPE-33932-pipeline
  identifier: PIPE33932pipeline
  tags: {}
  template:
    templateRef: PIPE33932pipeline
    versionLabel: v1
    gitBranch: master
    templateInputs:
      stages:
        - stage:
            identifier: sfd
            template:
              templateInputs:
                type: Approval
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: sfd
                          type: HarnessApproval
                          timeout: <+input>
                          spec:
                            approvers:
                              minimumCount: <+input>
                              userGroups: <+input>
        - stage:
            identifier: dfss
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: sdf
                      type: HarnessApproval
                      spec:
                        approvers:
                          minimumCount: <+input>
                          userGroups: <+input>
  projectIdentifier: adithya_test
  orgIdentifier: default
