pipeline:
  name: 17 oct demo pipeline112
  identifier: _oct_demo_pipeline112
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sdf
        identifier: sdf
        template:
          templateRef: oct_17_stage_demo
          versionLabel: ved
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: fds
                      type: HarnessApproval
                      spec:
                        approvers:
                          minimumCount: <+input>
                          userGroups: <+input>
