pipeline:
  name: create ouathsadfasd
  identifier: create_ouathsadfasd
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dgf
        identifier: dgf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fd
                  identifier: fd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
