pipeline:
  name: execP2_withRunTimeIS
  identifier: execP2_withRunTimeIS
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: jk
        identifier: jk
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fdg
                  identifier: fdg
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
