pipeline:
  name: inline to remote reff
  identifier: inline_to_remote_reff
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sdaf
        identifier: sdaf
        template:
          templateRef: stage_template_referencev
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: asdf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
