pipeline:
  name: isTemplatePipelineND
  identifier: isTemplatePipelineND
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: a
        identifier: a
        template:
          templateRef: isStagevND
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: sdf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
