pipeline:
  name: parent pipeline1123
  identifier: parent_pipeline1123
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: adsasd
        identifier: ads
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: child_pipeline1123
          project: AmitTest
          inputs:
            identifier: child_pipeline1123
            stages:
              - stage:
                  identifier: sadf
                  type: Approval
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: sadf
                            type: HarnessApproval
                            spec:
                              approvers:
                                userGroups: <+input>
