pipeline:
  name: parentNonDefault
  identifier: parentNonDefault
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: childNonDefaultBranch
          project: AmitTest
