pipeline:
  name: parent p456
  identifier: parent_p456
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sdf
        identifier: sdf
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: child_p678
          project: AmitTest
          inputs:
            identifier: child_p678
            stages:
              - stage:
                  identifier: sadf
                  type: Approval
                  spec:
                    execution:
                      steps:
                        - step:
                            identifier: sdf
                            type: HarnessApproval
                            spec:
                              approvers:
                                userGroups: <+input>
