pipeline:
  name: pipelinePreQaTest
  identifier: pipelinePreQaTest
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: a
        identifier: a
        template:
          templateRef: stageTestRepo2Main
          versionLabel: v2
