pipeline:
  name: pipeline demo main123
  identifier: pipeline_demo_main123
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sdf
        identifier: sdf
        template:
          templateRef: stage_tempalte_remote_pr123
          versionLabel: v123
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: adf
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
