pipeline:
  name: pipeline cds temp1
  identifier: pipeline_cds_temp1
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s2
        identifier: s2
        template:
          templateRef: mar21Stage6
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: ds
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>                          
