pipeline:
  name: pipeline cds temp1
  identifier: pipeline_cds_temp1
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: w1
                  identifier: w1
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
    - stage:
        name: s2
        identifier: s2
        template:
          templateRef: stage_cds
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: ds
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>    
    - stage:
        name: s3
        identifier: s3
        template:
          templateRef: stage_cds
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: ds
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>                          
