pipeline:
  name: remote pipeline v1
  identifier: remote_pipeline_v1
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: asda
        identifier: asda
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: ad
                  identifier: ad
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
