pipeline:
  name: sadgdfgsdfgsd12
  identifier: sadgdfgsdfgsd12
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  description: sdfgsdfgsdfg
  tags: {}
  stages:
    - stage:
        name: sdf
        identifier: sdf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: df
                  identifier: df
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    approverInputs: []
        tags: {}
