pipeline:
  name: sldkfjbgldsfkjgvblksdfbkvgsd
  identifier: sldkfjbgldsfkjgvblksdfbkvgsd
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: df
        identifier: df
        template:
          templateRef: june_22_stage
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: as
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
    - stage:
        name: s2
        identifier: s2
        template:
          templateRef: stage_ref_test
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: as
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
