pipeline:
  name: testBtaching
  identifier: testBtaching
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: mar21Stage1
          versionLabel: v1
    - stage:
        name: s2
        identifier: s2
        template:
          templateRef: mar21Stage2
          versionLabel: v1
    - stage:
        name: s3
        identifier: s3
        template:
          templateRef: mar21Stage3
          versionLabel: v1
    - stage:
        name: s4
        identifier: s4
        template:
          templateRef: mar21Stage4
          versionLabel: v1
    - stage:
        name: s5
        identifier: s5
        template:
          templateRef: mar21Stage5
          versionLabel: v1
    - stage:
        name: s6
        identifier: s6
        template:
          templateRef: mar21Stage6
          versionLabel: v1
