pipeline:
  name: test remote qw12
  identifier: test_remote_qw12
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sd
        identifier: sd
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sfd
                  identifier: sfd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
