pipeline:
  name: test qipeline test no default
  identifier: test_qipeline_test_no_default
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dsfsdf
        identifier: dsfdf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dsf
                  identifier: dsf
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
