pipeline:
  name: "test pipeline "
  identifier: test_pipeline
  tags: {}
  projectIdentifier: AmitTest
  orgIdentifier: default
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: s11
                  identifier: s11
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: s12
        identifier: s12
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: s123123
                  identifier: s123123
                  template:
                    templateRef: step_group_template2
                    versionLabel: sdf23123
                    gitBranch: aa_1master-patch
        tags: {}
