pipeline:
  name: test setup references defualt
  identifier: test_setup_references_defualt
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        template:
          templateRef: remote_stage_template_default
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: s1
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
