pipeline:
  name: test pipeline remote 123453
  identifier: test_pipeline_remote_123453
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fsd
        identifier: fsd
        template:
          templateRef: stage_cds
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: ds
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
