pipeline:
  name: testNPE_preqa
  identifier: testNPE_preqa
  projectIdentifier: TestAmit
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: dasf
        identifier: dasf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: asfd
                  identifier: asfd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
