pipeline:
  name: pipeline after move
  identifier: pipeline_after_move
  projectIdentifier: new_org_to_old_org
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s
        identifier: s
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fds
                  identifier: fds
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information update
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
