pipeline:
  name: asdfasdf
  identifier: asdfasdf
  tags: {}
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  stages:
    - stage:
        name: j
        identifier: j
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: bb_on_prem_test_pipeline
          project: GitX_Remote
          inputs: {}
