pipeline:
  name: dsvcasdv
  identifier: dsvcasdv
  projectIdentifier: GitX_Remote
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sdac
        identifier: sdac
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dsa
                  identifier: dsa
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
