pipeline:
  name: veryLongTextveryLongTextveryLongTextveryLongTextveryLongTextveryLongTextveryLongTextveryLongText
  identifier: remote_bulk_test
  projectIdentifier: demoProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fdc
        identifier: fdc
        tags: {}
        template:
          templateRef: stage_template_bulk
          versionLabel: da
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: as
                      type: HarnessApproval
                      spec:
                        approvers:
                          minimumCount: <+input>
                          userGroups: <+input>
