pipeline:
  name: remote pipeline
  identifier: remote_pipeline
  projectIdentifier: testProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ds
        identifier: ds
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: sd
                  identifier: sd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
